apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: {{ .Values.prometheus.scrape_enabled }}
    prometheus.io/job: {{ .Values.prometheus.job }}
    prometheus.io/path: {{ .Values.prometheus.metrics_path }}
    prometheus.io/port: {{ .Values.prometheus.port }}
    prometheus.io/label: {{ .Values.prometheus.label }}
  name: {{ include "appkube-security-rbac-service.fullname" . }}
  labels:
    {{- include "appkube-security-rbac-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "appkube-security-rbac-service.selectorLabels" . | nindent 4 }}
