apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: true
    prometheus.io/job: appkube-rbactest
    prometheus.io/path: /management/prometheus
    prometheus.io/port: '8094'
    prometheus.io/label: environment=devtest,app=appkube_rbactest
  name: {{ include "appkube-security-rbac-service.fullname" . }}
  labels:
    {{- include "appkube-security-rbac-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "appkube-security-rbac-service.selectorLabels" . | nindent 4 }}
